apiVersion: v1
kind: Pod
metadata:
  name: scylla-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: vdpa-net-a, vdpa-net-b
spec:
  containers:
  - name: scylla-pod
    image: scylla:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/cni/usrspcni/
      name: shared-dir
    - mountPath: /dev/hugepages
      name: hugepage
    - mountPath: /var/run/scylla/
      name: shared-scylla-dir
    resources:
      requests:
        #memory: 1Gi
        memory: 2Mi
        intel.com/vdpa_dpdk_a: '1'
        intel.com/vdpa_dpdk_b: '1'
      limits:
        #hugepages-1Gi: 2Gi
        hugepages-2Mi: 2048Mi
        intel.com/vdpa_dpdk_a: '1'
        intel.com/vdpa_dpdk_b: '1'
    #command: ["sleep", "infinity"]
  initContainers:
  - name: scylla-init-pod
    image: scylla-init-container:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    - mountPath: /var/lib/cni/usrspcni/
      name: shared-dir
    - mountPath: /var/run/scylla/
      name: shared-scylla-dir
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: shared-dir
    hostPath:
      path: /var/run/vdpa/vhost/
  - name: shared-scylla-dir
    hostPath:
      path: /var/run/scylla/
  - name: hugepage
    emptyDir:
      medium: HugePages
