## Deploys a traffic generator and a traffic sink on different nodes
## The node label "vdpa-test-role: gen" is used to place the generator pod
## The node label "vdpa-test-role: sink" is used to place the sink pod
# Eg:
# kubectl label nodes <gen-nodename> vdpa-test-role-gen=true
# kubectl label nodes <sink-nodename> vdpa-test-role-sink=true
apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod-gen
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
        "name": "vdpa-mlx-vhost-net",
        "mac": "0C:FE:C0:FF:EE:00"
      }
      ]'
spec:
  nodeSelector:
    vdpa-test-role-gen: "true"
  containers:
  - name: vdpa-example
    image: dpdk-app-devel:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
        #memory: 2Mi
        intel.com/vdpa_mlx_vhost: '1'
      limits:
        hugepages-1Gi: 2Gi
        #hugepages-2Mi: 2048Mi
        intel.com/vdpa_mlx_vhost: '1'
    env:
      - name: MAC
        value: "0C:FE:C0:FF:EE:00"
    command: ["./testpmd-wrapper.sh",
              "INTEL_COM_VDPA_MLX_VHOST",
              "-m", "1024",
              "--no-pci",
              "--iova-mode=va",
              "-l", "4,5",
              "--file-prefix=vdpa-test-gen",
              "--log-level pmd.net.virtio.init:debug",
              "--",
              "-a",
              "--stats-period", "2",
              "--forward-mode=txonly",
              "--eth-peer=0,0C:FE:C0:FF:EE:11"]
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: hugepage
    emptyDir:
      medium: HugePages
---
apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod-sink
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
        "name": "vdpa-mlx-vhost-net",
        "mac": "0C:FE:C0:FF:EE:11"
      }
      ]'
spec:
  nodeSelector:
    vdpa-test-role-sink: "true"
  containers:
  - name: vdpa-example
    image: dpdk-app-devel:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
        #memory: 2Mi
        intel.com/vdpa_mlx_vhost: '1'
      limits:
        hugepages-1Gi: 2Gi
        #hugepages-2Mi: 2048Mi
        intel.com/vdpa_mlx_vhost: '1'
    env:
      - name: MAC
        value: "0C:FE:C0:FF:EE:11"
    command: ["./testpmd-wrapper.sh",
              "INTEL_COM_VDPA_MLX_VHOST",
              "-m", "1024",
              "--no-pci",
              "--iova-mode=va",
              "-l", "0,1",
              "--file-prefix=vdpa-test-sink",
              "--log-level pmd.net.virtio.init:debug",
              "--",
              "-a",
              "--stats-period", "2",
              "--forward-mode=rxonly",
              "--eth-peer=0,0C:FE:C0:FF:EE:00"]
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: hugepage
    emptyDir:
      medium: HugePages
