apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vdpa-daemon-amd64
  labels:
    tier: node
    app:  uvdpad
    name: uvdpad
spec:
  selector:
    matchLabels:
      name: uvdpad
  template:
    metadata:
      labels:
        tier: node
        app:  uvdpad
        name: uvdpad
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: vdpadpdk-daemonset
        image: vdpa-daemonset:latest
        imagePullPolicy: Never
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
        securityContext:
          privileged: true
        volumeMounts:
        - name: vhostsock
          mountPath: /var/run/uvdpa/
          readOnly: false
        - name: log
          mountPath: /var/log
        - name: hugepage
          mountPath: /dev/hugepages
        resources:
          requests:
            memory: 2Mi
          limits:
            hugepages-2Mi: 2048Mi
        #command: ["sleep", "infinity"]
      volumes:
        - name: vhostsock
          hostPath:
            path: /var/run/uvdpa/
        - name: log
          hostPath:
            path: /var/log
        - name: hugepage
          emptyDir:
            medium: HugePages
