apiVersion: v1
kind: Pod
metadata:
  name: example1
    #annotations:
    #    v1.multus-cni.io/default-network: default-ovnkube-sriov
spec:
  containers:
    - name: test
      image: praqma/network-multitool
      imagePullPolicy: Never
      command:
        - sleep
        - infinity
---
apiVersion: v1
kind: Pod
metadata:
  name: example2
    #annotations:
    #    v1.multus-cni.io/default-network: default-ovnkube-sriov
spec:
  containers:
    - name: test
      image: praqma/network-multitool
      imagePullPolicy: Never
      command:
        - sleep
        - infinity
